name: hive_flutter
description: Extension for Hive. Makes it easier to use Hive in Flutter apps.
version: 0.2.1
author: Simon Leier <simonleier@gmail.com>
homepage: https://github.com/leisim/hive

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive:
    git: 
      url: https://github.com/daanporon/hive.git
      ref: delete-if-exists

dev_dependencies:
  flutter_test:
    sdk: flutter
